### PR TITLE
LRAC-13626 - Add aria-label to each ClayButton that has only the ClayIcon inside.

### PR DESCRIPTION
**Pull request by ilzamcmed**
jira issue: https://issues.liferay.com/browse/LRAC-13626

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Resent to https://github.com/interaminense/liferay-portal/pull/355 to resolve conflicts

**Pull request closed without merging**
