### PR TITLE
LPS-114003 Fix action to delete field from object

### PR DESCRIPTION
**Pull request by interaminense**
cc: @brunofarache

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:appbuilder

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by interaminense** [comment]
ci:test:appbuilder

**Comment by interaminense** [comment]
ci:test:relevant

**Pull request closed without merging**
