### PR TITLE
LRAC-8284 [F][B] Send title property when fire event rating

### PR DESCRIPTION
**Pull request by interaminense**
Jira issue: https://issues.liferay.com/browse/LRAC-8284

### CODE REVIEW

**Comment by interaminense** [comment]
cc: @kienD, @inacionery

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Review by kienD — COMMENTED** [review]
lgtm

**Pull request closed without merging**
