### PR TITLE
LPS-116482 Receive modal content from props

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
I need to read Brian's comment

**Comment by rebsilva** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Vou fechar esse PR pq ja está com Brian!

**Pull request closed without merging**
