### PR TITLE
LPS-117969 use defaultLanguageId from object instead fixed value

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/177

**Pull request closed without merging**
