### PR TITLE
LPS-112767 warn the user about the impacts of propagating changes on a fields

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to https://github.com/interaminense/liferay-portal/pull/124

**Pull request closed without merging**
