### PR TITLE
LPS-117969 Set editingLanguageId in the EditApp component

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/179

**Pull request closed without merging**
