### PR TITLE
LPS-116543 No need for this test anymore since the validation is gone

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/134

**Pull request closed without merging**
