### PR TITLE
LPS-118586 add fetcher on useResource config

### PR DESCRIPTION
**Pull request by kevenleone**
cc: @albinojunior, @matuzalemsteles, @diegonvs, @gabrielwas

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by jpince** [comment]
@interaminense can you please either:
1. `ci:test:relevant` and wait for the result
1. `ci:forward`

When you do both, CI runs tests twice, slowing down everyone's pull requests (including your own). `ci:stop` can't specifically cancel the second build, so we'll just let them both run for now. Just knowledge for the future :smile:

**Comment by interaminense** [comment]
Sorry, @jpince. I didn't see that I ran the `ci:test:relevant` before `ci:forward`. I'll pay more attention to this from now on. Thank you

**Pull request closed without merging**
