### PR TITLE
[F] Upgrade Clay Form (All Fields) component to latest version

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13325

### CODE REVIEW

**Comment by fmarcio** [comment]
hey guys, I think the diff is in the PR is too big. Do you think this is normal? I just updated `@clayui/form` normally

**Comment by interaminense** [comment]
@fmarcio could you rebase and resolve the conflict?

**Comment by fmarcio** [comment]
> @fmarcio could you rebase and resolve the conflict?

done!

**Comment by interaminense** [comment]
Resent to https://github.com/liferay-ac/liferay-portal/pull/422

**Pull request closed without merging**
