### PR TITLE
LPS-118749 Add thunk pageLanguageUpdate

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
Os commits de Jeyvison neste PR estão aguardando o merge de Brian. Está quebrado os fields que tem options, ver com Matu isso amanhã

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
resent to: https://github.com/jeyvison/liferay-portal/pull/852

**Pull request closed without merging**
