### PR TITLE
LPS-114462 SF

### PR DESCRIPTION
**Pull request by interaminense**
cc: @gabrielwas @leoadb @jeyvison

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
resent to https://github.com/gabrielwas/liferay-portal/pull/163

**Pull request closed without merging**
