### PR TITLE
LRAC-3501 Semver

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1928. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
