### PR TITLE
LPS-115587 Fix app name field with wrong top and bottom margins

### PR DESCRIPTION
**Pull request by rebsilva**

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
