### PR TITLE
LPS-113702 SF

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
see https://github.com/jeyvison/liferay-portal/pull/764

**Comment by jeyvison** [comment]
ci:close

**Pull request closed without merging**
