### PR TITLE
LPS-117585 Add null name validation for custom object, form view and table view

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
@jeyvison, can you take a look at the java code? Thanks.

**Comment by jeyvison** [comment]
@gabrielwas @interaminense LGTM

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/236

**Pull request closed without merging**
