### PR TITLE
LPS-113702 baseline

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/111

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
