### PR TITLE
LRAC-11931 Send blog current title as part of the Comment event

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue https://issues.liferay.com/browse/LRAC-11931

### CODE REVIEW

**Comment by interaminense** [comment]
cc: @marcellustavares

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
:rocket:  LGTM

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
