### PR TITLE
LRAC-11932 Add document title to AC rating event

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue https://issues.liferay.com/browse/LRAC-11932

### CODE REVIEW

**Review by ilzamcmed — APPROVED** [review]
LGTM :rocket:

**Comment by interaminense** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:reevaluate:1377401_5343

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:reevaluate:1377401_5343

**Comment by interaminense** [comment]
ci:reevaluate:1377401_5343

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
