### PR TITLE
LPS-118859 Enable fieldset layout edition only for fields group and Remove empty spaces from non editable layout

### PR DESCRIPTION
**Pull request by albinojunior**
cc: @mateussgn @rebsilva @oliveiraaraujo

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
