### PR TITLE
LPS-87289 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by john-co** [comment]
@interaminense fyi, In order to have the frontend-js test batch available for other pull requests,
we temporarily ignored the analytics-client-js tests here: https://github.com/jpince/liferay-portal/pull/93#issuecomment-439543648

When the fix is ready, can you please turn back on the analytics-client-js tests? Thank you.

**Comment by interaminense** [comment]
Right, @john-co. I'll do this right now.

**Comment by interaminense** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65102. [See changes here.](https://github.com/interaminense/liferay-portal/compare/d68c488df7eb~1...d68c488df7eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
