### PR TITLE
LPS-118749 Use defaultLanguageId from dataDefinition when save and list an entry

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:teste:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/212

**Pull request closed without merging**
