### PR TITLE
LPS-114549 Iterate over the fields when listing rules, including nested fields

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/160

**Pull request closed without merging**
