### PR TITLE
LPS-118853 Fix translation synchronization of options label

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
@albinojunior Precisamos ver se esse fix vai impactar o time do Forms

**Comment by albinojunior** [comment]
ci:test:forms

**Comment by albinojunior** [comment]
cc: @palomaanunes

**Comment by interaminense** [comment]
ci:forward

**Comment by palomaanunes** [comment]
@albinojunior according to the result of ci:test:form (❌ ci:test:forms - 65 out of 80 jobs passed in 1 hour 10 minutes) your PR did not fail the automated tests of Forms. From our perspective, this PR is good to go!

**Pull request closed without merging**
