### PR TITLE
LPS-119844 Adapt components to accept Repeatable fields values

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by jpince** [comment]
semver failure is due to Brian Chan publishing right now. I don't know about the failure in `DataLayoutResourceTest.testPostDataLayoutContext`

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
@interaminense @kevenleone @jpince  I'm verifying the test error

**Comment by jeyvison** [comment]
see https://github.com/jeyvison/liferay-portal/pull/878

**Comment by jpince** [comment]
thanks @jeyvison. I assigned https://issues.liferay.com/browse/LPS-119844 to you and updated the PR URL in the ticket

**Comment by interaminense** [comment]
I'm closing this PR because it was sent to https://github.com/jeyvison/liferay-portal/pull/878

**Pull request closed without merging**
