### PR TITLE
LPS-118749 Add thunk pageLanguageUpdate

### PR DESCRIPTION
**Pull request by interaminense**
cc: @oliveiraaraujo, @matuzalemsteles, @diegonvs

### CODE REVIEW

**Comment by interaminense** [comment]
Esperar alguns fixs que Jeyvison mandou pra Brian e depois remover o commit WIP antes de enviar pra frente.

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/interaminense/liferay-portal/pull/219

**Pull request closed without merging**
