### PR TITLE
LPS-112510 Disable save button when DataLayout has no fields

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by interaminense** [comment]
LGTM

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
ci:foward

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
